const AUTH = {
    INIT_AUTH: 'AUTH-INIT',
    AUTH_SUCCESS: 'AUTH-SUCCESS',
    AUTH_ERROR: 'AUTH-ERROR',
    LOGOUT: 'AUTH-LOGOUT'
}

const MODAL = {
    SHOW_MODAL: 'SHOW-MODAL',
    HIDE_MODAL: 'HIDE-MODAL'
}


const AUTH_TYPE = {
    GOOGLE: 'GOOGLE-AUTH',
    BASIC: 'BASIC-AUTH'
}


export { AUTH, MODAL, AUTH_TYPE }

